[workspace]
resolver = "3"
members = [
    "crates/mev-bot",
    "crates/mev-core",
    "crates/mev-hl-client",
    "crates/mev-hyperevm",
    "crates/mev-metrics",
    "crates/mev-risk",
    "crates/mev-strategy",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.90"
license = "MIT"
repository = "https://github.com/garyb9/mev-bot"

[workspace.dependencies]
mev-core = { path = "crates/mev-core" }
mev-hl-client = { path = "crates/mev-hl-client" }
mev-hyperevm = { path = "crates/mev-hyperevm" }
mev-metrics = { path = "crates/mev-metrics" }
mev-risk = { path = "crates/mev-risk" }
mev-strategy = { path = "crates/mev-strategy" }

rust_decimal = "1.43"

[profile.release]
lto = "thin"
codegen-units = 1
panic = "abort"
